apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yijf8sz2c-dotnet-basic
  janus-idp.io/tekton: yijf8sz2c-dotnet-basic
  backstage.io/kubernetes-id: yijf8sz2c-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yijf8sz2c-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
